### PR TITLE
Internationalization Dropdown w/ next-i18next

### PR DESCRIPTION
**Pull request by jmichaliga**
This route makes certain we don't load ALL of the translations at runtime. 

TODO: still a bit to get the translations into non-server side rendered pieces of the app.

### CODE REVIEW

**Review by GarrettJMU — APPROVED** [review]
[nit] - update t in the de-structure of that hook to translate for readability

**Review by GarrettJMU — CHANGES_REQUESTED** [review]
Actually when changing on pages it seems to redirect up to the home page

We should also add persistence to this. Check if there is a value in localStorage maybe and set one there?

**Comment by ctjlewis** [comment]
Final nit: Can we add `passHref` to all `NextLink` components? Super sorry.

**Review by GarrettJMU — APPROVED** [review]
LGTM

**Comment by jmichaliga** [comment]
> Final nit: Can we add `passHref` to all `NextLink` components? Super sorry.

Added.

**Comment by ctjlewis** [comment]
Thanks @jmichaliga, Next should set it by default. It just makes sure that the rendered links take form `<a href="...">`, for accessibility etc.

**Pull request merged**
