### PR TITLE
Add in next links

### PR DESCRIPTION
**Pull request by GarrettJMU**

### CODE REVIEW

**Comment by ctjlewis** [comment]
@GarrettJMU, nit: Can you add `passHref` flag also? Build failing cause of TypeError, mad that `props.href` can be undefined.

**Comment by ctjlewis** [comment]
You can run `yarn build` locally to mimic the Deploy behavior.

**Comment by GarrettJMU** [comment]
Trying to be lazy and fix these - but yes that's prob best lol @ctjlewis

**Comment by GarrettJMU** [comment]
Should be good now @ctjlewis

**Comment by ctjlewis** [comment]
1s

**Comment by ctjlewis** [comment]
Also added pre-push hooks in #109, so local environment will block push if deploy would fail.

**Pull request merged**
